In [1]:
# -*- coding: utf-8 -*-

import sqlite3 as sl
import pandas as pd

In [14]:
con = sl.connect("dados_fies.db")
cur = con.cursor()
banco_de_dados = """BEGIN TRANSACTION;
--DROP TABLE IF EXISTS "Estudante";
CREATE TABLE IF NOT EXISTS "Estudante" (
	"CO_INSCRICAO_EXT_ALUNOS"	INTEGER,
	"CO_CONTRATO_FIES_EXT_ALUNOS"	INTEGER,
	"CO_IES_EXT_ALUNOS"	INTEGER,
	"NU_PERCENTUAL_PROUNI"	REAL,
	"NU_PERCENT_SOLICITADO_FINANC"	REAL,
	"DT_NASCIMENTO"	DATE,
	"ST_DEFICIENCIA"	TEXT,
	"ST_ENSINO_MEDIO_ESCOLA_PUBLICA"	TEXT,
	"CO_CIDADE"	INTEGER,
	"SG_SEXO"	TEXT,
	"DS_SEXO"	TEXT,
	"CO_ESTADO_CIVIL"	INTEGER,
	"DS_ESTADO_CIVIL"	TEXT,
	"SG_RACA_COR"	TEXT,
	"VL_MENSALIDADE_EXT_ALUNOS"	REAL,
	"CO_ADITAMENTO_EXT_ALUNOS"	INTEGER,
	--"NU_ANO_PROC" INTEGER,
    --"NU_MES_PROC" INTEGER,
    PRIMARY KEY("CO_INSCRICAO_EXT_ALUNOS","CO_CONTRATO_FIES_EXT_ALUNOS","CO_ADITAMENTO_EXT_ALUNOS"),
	FOREIGN KEY("CO_CIDADE") REFERENCES "Municipio"("CO_MUNICIPIO"),
	FOREIGN KEY("CO_IES_EXT_ALUNOS") REFERENCES "IES"("CO_IES"),
	FOREIGN KEY("CO_INSCRICAO_EXT_ALUNOS") REFERENCES "PROCESSO"("CO_INSCRICAO")
);
--DROP TABLE IF EXISTS "Mantenedoura";
CREATE TABLE IF NOT EXISTS "Mantenedoura" (
	"CO_MANTENEDORA"	INTEGER,
	"NU_CNPJ_MANTENEDORA"	INTEGER,
	"NO_RAZAO_SOCIAL_MANTENEDORA"	TEXT,
	"CO_MUNICIPIO_MANTENEDORA"	INTEGER,
	PRIMARY KEY("CO_MANTENEDORA","NU_CNPJ_MANTENEDORA"),
	FOREIGN KEY("CO_MUNICIPIO_MANTENEDORA") REFERENCES "Municipio"("CO_MUNICIPIO")
);
--DROP TABLE IF EXISTS "Curso";
CREATE TABLE IF NOT EXISTS "Curso" (
	"DS_CURSO"	INTEGER ,
	"CO_CURSO"	INTEGER ,
	"CO_IES"	INTEGER ,
    "CO_TIPO_CURSO" INTEGER,
    "DS_TIPO_CURSO" TEXT,
    "CO_PERIODICIDADE_CUR" INTEGER,
    "DS_PERIODICIDADE_CUR" TEXT,
    PRIMARY KEY("CO_CURSO", "CO_IES"),
	FOREIGN KEY("CO_IES") REFERENCES "IES"("CO_IES")
);
--DROP TABLE IF EXISTS "IES";
CREATE TABLE IF NOT EXISTS "IES" (
	"CO_IES"	INTEGER ,
	"CO_CAMPUS"	INTEGER ,
    "NO_IES"	TEXT ,
	"CO_MUNICIPIO_IES"	INTEGER ,
	"NO_CAMPUS"	TEXT ,
	PRIMARY KEY("CO_IES","CO_CAMPUS"),
	FOREIGN KEY("CO_MUNICIPIO_IES") REFERENCES "Municipio"("CO_MUNICIPIO")
);
DROP TABLE IF EXISTS "Processo";
CREATE TABLE IF NOT EXISTS "Processo" (
	"CO_PROCESSO"	INTEGER,
	"CO_INSCRICAO"	INTEGER,
    "CO_ADITAMENTO" INTEGER,
 	"CO_MANTENEDORA"	INTEGER,
	"CO_CURSO"	INTEGER,
	"CO_AGENTE_FINANCEIRO"	INTEGER,
	"NO_AGENTE_FINANCEIRO"	TEXT,
	"VL_SEMESTRE"	REAL,
	"TP_FIANCA"	TEXT,
	"VL_REPASSE"	REAL,
	"VL_PERC_FINANCIAMENTO"	REAL,
	"QT_SEMESTRE_FINANCIADO"	INTEGER,
    "NU_ANO" INTEGER,
	PRIMARY KEY("CO_PROCESSO","CO_INSCRICAO","CO_ADITAMENTO"),
	FOREIGN KEY("CO_MANTENEDORA") REFERENCES "Mantenedoura"("CO_MANTENEDORA"),
	FOREIGN KEY("CO_CURSO") REFERENCES "Curso"("CO_CURSO")
);
--DROP TABLE IF EXISTS "Municipio";
CREATE TABLE IF NOT EXISTS "Municipio" (
	"SG_UF"	TEXT,
	"NO_MUNICIPIO"	TEXT,
    "CO_MUNICIPIO"	INTEGER,
    PRIMARY KEY("CO_MUNICIPIO")
    
);
COMMIT;
"""
cur.executescript(banco_de_dados)
print("Banco de dados criado com sucesso")

Banco de dados criado com sucesso

tabela IES

In [3]:
import csv
dados_carregados = []
with open('FINANCIAMENTO_CONCEDIDOS_SEMESTRE_1_2011.csv','r') as arquivo:
        reader = csv.reader(arquivo, delimiter=';')
        for row in reader:
                linha_carregada = [row[6], row[39], row[7],row[8], row[40]]
                if not linha_carregada in dados_carregados:
                    cur.execute("INSERT INTO IES VALUES (?,?,?,?,?);", linha_carregada)
                    dados_carregados.append(linha_carregada)
con.commit()
print("Tabela Carregada com sucesso")

Tabela Carregada com sucesso

tabela Estudante

In [4]:
import csv
dados_carregados = []
with open('FINANCIAMENTO_CONCEDIDOS_SEMESTRE_1_2011.csv','r') as arquivo:
        reader = csv.reader(arquivo, delimiter=';')
        for row in reader:
                linha_carregada = [row[35], row[36], row[37],row[22], row[23], row[25], row[26],row[27], row[28], row[29], row[30], row[31], row[32], row[33], row[42], row[44]]
                if not linha_carregada in dados_carregados:
                    cur.execute("INSERT INTO Estudante VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);", linha_carregada)
                    dados_carregados.append(linha_carregada)
con.commit()
print("Tabela Carregada com sucesso")

Tabela Carregada com sucesso

tabela Mantenedoura

In [5]:
import csv
dados_carregados = []
with open('FINANCIAMENTO_CONCEDIDOS_SEMESTRE_1_2011.csv','r') as arquivo:
        reader = csv.reader(arquivo, delimiter=';')
        for row in reader:
                linha_carregada = [row[2], row[3], row[4],row[5]]
                if not linha_carregada in dados_carregados:
                    cur.execute("INSERT INTO Mantenedoura VALUES (?,?,?,?);", linha_carregada)
                    dados_carregados.append(linha_carregada)
con.commit()
print("Tabela Carregada com sucesso")

Tabela Carregada com sucesso

tabela Curso

In [6]:
import csv
dados_carregados = []
with open('FINANCIAMENTO_CONCEDIDOS_SEMESTRE_1_2011.csv','r') as arquivo:
        reader = csv.reader(arquivo, delimiter=';')
        for row in reader:
                linha_carregada = [row[46], row[45], row[6],row[47],row[48],row[49],row[50]]
                if not linha_carregada in dados_carregados:
                    cur.execute("INSERT INTO Curso VALUES (?,?,?,?,?,?,?);", linha_carregada)
                    dados_carregados.append(linha_carregada)
con.commit()
print("Tabela Carregada com sucesso")

Tabela Carregada com sucesso

tabela Processo

In [ ]:
import csv
dados_carregados = []
with open('FINANCIAMENTO_CONCEDIDOS_SEMESTRE_1_2011.csv','r') as arquivo:
        reader = csv.reader(arquivo, delimiter=';')
        for row in reader:
                linha_carregada = [row[9], row[19], row[11], row[2],row[45], row[12], row[13], row[51], row[20], row[24], row[41], row[43], row[17]]
                if not linha_carregada in dados_carregados:
                    cur.execute("INSERT INTO Processo VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?);", linha_carregada)
                    dados_carregados.append(linha_carregada)
con.commit()
print("Tabela Carregada com sucesso")

tabela Municipio

In [8]:
import csv
dados_carregados = []
with open('CIDADES.csv','r') as arquivo:
        reader = csv.reader(arquivo, delimiter=';')
        for row in reader:
                linha_carregada = [row[0], row[2], row[1]]
                if not linha_carregada in dados_carregados:
                    cur.execute("INSERT INTO Municipio VALUES (?,?,?);", linha_carregada)
                    dados_carregados.append(linha_carregada)
con.commit()
print("Tabela Carregada com sucesso")

Tabela Carregada com sucesso

In [12]:
con.commit()
dfq1 = pd.read_sql_query("SELECT * FROM Processo",con)
dfq1

,CO_PROCESSO,CO_INSCRICAO,CO_MANTENEDORA,CO_CURSO,CO_AGENTE_FINANCEIRO,NO_AGENTE_FINANCEIRO,VL_SEMESTRE,TP_FIANCA,VL_REPASSE,VL_PERC_FINANCIAMENTO,QT_SEMESTRE_FINANCIADO,NU_ANO
0,52,6624,1534,54042,104,Caixa Econômica Federal,2727,N,"28988,82",75.0,9,2011
1,53,6624,1534,54042,104,Caixa Econômica Federal,2727,N,"28988,82",75.0,9,2011
2,52,20079,1534,54042,104,Caixa Econômica Federal,"1999,7",N,"15177,08",50.0,7,2011
3,53,20079,1534,54042,104,Caixa Econômica Federal,"1999,7",N,"15177,08",50.0,7,2011
4,52,30766,1534,54042,104,Caixa Econômica Federal,"1818,38",N,"19326,64",50.0,9,2011
5,53,30766,1534,54042,104,Caixa Econômica Federal,"1818,38",N,"19326,64",50.0,9,2011
6,52,52565,1534,88559,104,Caixa Econômica Federal,"2617,75",N,"26072,76",50.0,9,2011
7,53,52565,1534,88559,104,Caixa Econômica Federal,"2617,75",N,"26072,76",50.0,9,2011
8,52,119513,1534,54042,104,Caixa Econômica Federal,"2909,4",N,"30922,6",80.0,9,2011
9,53,119513,1534,54042,104,Caixa Econômica Federal,"2909,4",N,"30922,6",80.0,9,2011
10,53,191513,1534,54042,104,Caixa Econômica Federal,"1999,7",N,"15175,01",50.0,7,2011
11,51,273063,1534,90665,104,Caixa Econômica Federal,1818,N,"6000,91",50.0,10,2011
12,52,273063,1534,90665,104,Caixa Econômica Federal,1818,N,"6000,91",50.0,10,2011
13,53,273063,1534,90665,104,Caixa Econômica Federal,1818,N,"6000,91",50.0,10,2011
14,51,301174,1534,88559,1,Banco do Brasil,"3926,6",N,"53094,61",75.0,10,2011
15,52,301174,1534,88559,1,Banco do Brasil,"3926,6",N,"53094,61",75.0,10,2011
16,53,301174,1534,88559,1,Banco do Brasil,"3926,6",N,"53094,61",75.0,10,2011
17,53,321167,1534,90665,104,Caixa Econômica Federal,"2909,4",N,"19123,26",80.0,10,2011
18,52,321188,1534,88559,104,Caixa Econômica Federal,"4362,06",N,"25622,84",100.0,4,2011
19,53,321188,1534,88559,104,Caixa Econômica Federal,"4362,06",N,"25622,84",100.0,4,2011
20,49,323998,1534,88559,104,Caixa Econômica Federal,"2617,74",N,"28781,04",50.0,10,2011
21,51,323998,1534,88559,104,Caixa Econômica Federal,"2617,74",N,"28781,04",50.0,10,2011
22,52,323998,1534,88559,104,Caixa Econômica Federal,"2617,74",N,"28781,04",50.0,10,2011
23,53,323998,1534,88559,104,Caixa Econômica Federal,"2617,74",N,"28781,04",50.0,10,2011
24,49,324769,1534,88559,104,Caixa Econômica Federal,"3358,78",N,"6717,56",70.0,10,2011
25,51,324769,1534,88559,104,Caixa Econômica Federal,"3358,78",N,"6717,56",70.0,10,2011
26,52,324769,1534,88559,104,Caixa Econômica Federal,"3358,78",N,"6717,56",70.0,10,2011
27,53,324769,1534,88559,104,Caixa Econômica Federal,"3358,78",N,"6717,56",70.0,10,2011
28,49,327362,1534,88559,104,Caixa Econômica Federal,5232,N,"51735,96",100.0,10,2011
29,51,327362,1534,88559,104,Caixa Econômica Federal,5232,N,"51735,96",100.0,10,2011
...,...,...,...,...,...,...,...,...,...,...,...,...
2746,52,250864,440,15448,104,Caixa Econômica Federal,5197,N,21869,100.0,4,2011
2747,53,250864,440,15448,104,Caixa Econômica Federal,5197,N,21869,100.0,4,2011
2748,49,255877,440,15448,104,Caixa Econômica Federal,"5781,96",N,"15665,96",100.0,8,2011
2749,51,255877,440,15448,104,Caixa Econômica Federal,"5781,96",N,"15665,96",100.0,8,2011
2750,52,255877,440,15448,104,Caixa Econômica Federal,"5781,96",N,"15665,96",100.0,8,2011
2751,53,255877,440,15448,104,Caixa Econômica Federal,"5781,96",N,"15665,96",100.0,8,2011
2752,53,260216,440,15443,104,Caixa Econômica Federal,"1653,75",N,15288,75.0,7,2011
2753,52,279570,440,98957,104,Caixa Econômica Federal,2390,N,10285,100.0,4,2011
2754,53,279570,440,98957,104,Caixa Econômica Federal,2390,N,10285,100.0,4,2011
2755,49,372647,440,109642,104,Caixa Econômica Federal,1755,N,7725,75.0,4,2011
2756,51,372647,440,109642,104,Caixa Econômica Federal,1755,N,7725,75.0,4,2011
2757,52,372647,440,109642,104,Caixa Econômica Federal,1755,N,7725,75.0,4,2011
2758,53,372647,440,109642,104,Caixa Econômica Federal,1755,N,7725,75.0,4,2011
2759,52,376475,440,15448,104,Caixa Econômica Federal,5897,N,46949,100.0,8,2011
2760,53,376475,440,15448,104,Caixa Econômica Federal,5897,N,46949,100.0,8,2011
2761,51,423244,440,109652,104,Caixa Econômica Federal,"1436,4",N,"6848,4",75.0,4,2011
2762,52,423244,440,109652,104,Caixa Econômica Federal,"1436,4",N,"6848,4",75.0,4,2011
2763,53,423244,440,109652,104,Caixa Econômica Federal,"1436,4",N,"6848,4",75.0,4,2011
2764,51,424189,440,109652,104,Caixa Econômica Federal,1241,N,5221,50.0,4,2011
2765,52,424189,440,109652,104,Caixa Econômica Federal,1241,N,5221,50.0,4,2011
2766,53,424189,440,109652,104,Caixa Econômica Federal,1241,N,5221,50.0,4,2011
2767,51,426418,440,15448,104,Caixa Econômica Federal,6652,N,59027,100.0,8,2011
2768,52,426418,440,15448,104,Caixa Econômica Federal,6652,N,59027,100.0,8,2011
2769,53,426418,440,15448,104,Caixa Econômica Federal,6652,N,59027,100.0,8,2011
2770,53,427614,440,109652,104,Caixa Econômica Federal,"1157,1",N,"4499,1",75.0,4,2011
2771,52,470411,440,109642,104,Caixa Econômica Federal,"1861,5",N,"8146,5",75.0,4,2011
2772,53,470411,440,109642,104,Caixa Econômica Federal,"1861,5",N,"8146,5",75.0,4,2011
2773,53,490123,440,119261,104,Caixa Econômica Federal,1596,N,8812,100.0,6,2011
2774,52,2393,656,95047,104,Caixa Econômica Federal,"2951,97",N,"30150,96",50.0,10,2010
2775,52,14362,656,73259,104,Caixa Econômica Federal,"4306,38",N,"35974,5",100.0,8,2011

In [42]:
#1 mostrar os nomes de todos os cursos de Licenciatura financiados pelo FIES
con.commit()
sqlquery="""
select distinct DS_CURSO from Curso 
where CO_CURSO IN (
select distinct CO_CURSO from Processo) and DS_TIPO_CURSO='Licenciatura'
"""
dfq1 = pd.read_sql_query(sqlquery,con)
dfq1

                                             DS_CURSO
0                                           FILOSOFIA
1                                           PEDAGOGIA
2                                              LETRAS
3                                     EDUCAÇÃO FÍSICA
4                                          MATEMÁTICA
5                                            HISTÓRIA
6                                              FÍSICA
7                                             QUÍMICA
8                                 CIÊNCIAS BIOLÓGICAS
9                                           GEOGRAFIA
10                        LETRAS - PORTUGUÊS E INGLÊS
11                         LETRAS - LÍNGUA PORTUGUESA
12                                           BIOLOGIA
13                                    ESTUDOS SOCIAIS
14                                      ARTES VISUAIS
15                                           CIÊNCIAS
16                      LETRAS - PORTUGUÊS E ESPANHOL
17                                    LETRAS - INGLÊS
18                                         PSICOLOGIA
19                                   LETRAS - FRANCÊS
20                                 LETRAS - PORTUGUÊS
21  LETRAS PORTUGUÊS E ESPANHOL E RESPECTIVAS LITE...
22                                        INFORMÁTICA
23                                             MÚSICA
24                          GEOGRAFIA E MEIO AMBIENTE
25                                         SOCIOLOGIA
26                                         ENFERMAGEM
27                                   CIÊNCIAS SOCIAIS
28                                              ARTES
29                                  LETRAS - ESPANHOL

In [7]:
#2 mostrar os códigos de contrato de todos os estudantes do FIES com alguma deficiência
con.commit()
sqlquery="""
select CO_CONTRATO_FIES_EXT_ALUNOS from Estudante 
where ST_DEFICIENCIA='S'
"""
dfq1 = pd.read_sql_query(sqlquery,con)
dfq1

     CO_CONTRATO_FIES_EXT_ALUNOS
0                         205320
1                         286937
2                         238981
3                         249914
4                         118899
5                         261774
6                         125273
7                         193206
8                         252890
9                         129085
10                        185352
11                        162198
12                        185744
13                        159430
14                        260980
15                        237497
16                        135702
17                        135702
18                        246127
19                        146457
20                        291153
21                        268179
22                        285475
23                        288201
24                        234203
25                        231268
26                        297466
27                        250949
28                        183172
29                        236100
..                           ...
537                       168617
538                       261636
539                       285669
540                       184329
541                       158140
542                       253040
543                       123232
544                       123232
545                       114250
546                       124430
547                       253900
548                       157384
549                       203485
550                       173561
551                       256915
552                       246170
553                       283044
554                       283727
555                       243117
556                       294942
557                       240720
558                       232220
559                       260505
560                       283212
561                       275221
562                       288300
563                       276960
564                       290604
565                       288040
566                       296464

[567 rows x 1 columns]

In [43]:
#1 mostrar os nomes de todos os cursos de Licenciatura financiados pelo FIES
con.commit()
sqlquery="""
select distinct DS_CURSO from Curso natural join Processo
where DS_TIPO_CURSO='Licenciatura'
"""
dfq1 = pd.read_sql_query(sqlquery,con)
dfq1

                                             DS_CURSO
0                                     EDUCAÇÃO FÍSICA
1                                 CIÊNCIAS BIOLÓGICAS
2                                          ENFERMAGEM
3                                             QUÍMICA
4                                           PEDAGOGIA
5                                          PSICOLOGIA
6                                           FILOSOFIA
7                                              LETRAS
8                                            HISTÓRIA
9                                  LETRAS - PORTUGUÊS
10                                         MATEMÁTICA
11                                    LETRAS - INGLÊS
12                         LETRAS - LÍNGUA PORTUGUESA
13                        LETRAS - PORTUGUÊS E INGLÊS
14                      LETRAS - PORTUGUÊS E ESPANHOL
15                                          GEOGRAFIA
16                                             FÍSICA
17                                             MÚSICA
18                                   CIÊNCIAS SOCIAIS
19                          GEOGRAFIA E MEIO AMBIENTE
20  LETRAS PORTUGUÊS E ESPANHOL E RESPECTIVAS LITE...
21                                      ARTES VISUAIS
22                                           CIÊNCIAS
23                                        INFORMÁTICA
24                                   LETRAS - FRANCÊS
25                                  LETRAS - ESPANHOL
26                                           BIOLOGIA
27                                    ESTUDOS SOCIAIS
28                                              ARTES
29                                         SOCIOLOGIA

In [27]:
#3 mostrar todos os processos feitos para estudantes casados
con.commit()
sqlquery="""
select * from Processo 
where CO_INSCRICAO in (
select CO_INSCRICAO_EXT_ALUNOS from Estudante
where CO_ESTADO_CIVIL=2
)
order by CO_INSCRICAO
"""
dfq1 = pd.read_sql_query(sqlquery,con)
dfq1

,CO_PROCESSO,CO_INSCRICAO,CO_ADITAMENTO,CO_MANTENEDORA,CO_CURSO,CO_AGENTE_FINANCEIRO,NO_AGENTE_FINANCEIRO,VL_SEMESTRE,TP_FIANCA,VL_REPASSE,VL_PERC_FINANCIAMENTO,QT_SEMESTRE_FINANCIADO,NU_ANO
0,52,643,27065,127,5206,104,Caixa Econômica Federal,20178,N,218400,100.0,10,2011
1,53,643,27065,127,5206,104,Caixa Econômica Federal,20178,N,218400,100.0,10,2011
2,53,1050,0,1965,97932,104,Caixa Econômica Federal,"2530,2",F,"21871,65",100.0,8,2011
3,52,1342,27070,508,67959,104,Caixa Econômica Federal,"2340,46",N,"26044,59",80.0,9,2011
4,53,1342,27070,508,67959,104,Caixa Econômica Federal,"2340,46",N,"26044,59",80.0,9,2011
5,53,1372,43322,1174,48610,104,Caixa Econômica Federal,"3886,2",F,"15667,32",100.0,4,2011
6,52,1483,25182,1204,59827,104,Caixa Econômica Federal,"3757,5",N,"44438,67",75.0,8,2010
7,53,1483,46205,1204,59827,104,Caixa Econômica Federal,"4129,56",N,"44438,67",75.0,8,2011
8,44,1488,19832,1040,91011,104,Caixa Econômica Federal,"2857,5",N,"24163,99",75.0,8,2010
9,53,1554,0,11,964,104,Caixa Econômica Federal,2748,N,"59874,72",100.0,10,2011
10,53,1625,0,1204,92083,104,Caixa Econômica Federal,"2521,17",S,"10563,66",75.0,4,2011
11,52,1703,25587,3052,72933,104,Caixa Econômica Federal,"6458,46",N,"19752,08",100.0,5,2010
12,52,1709,24440,647,17531,104,Caixa Econômica Federal,"3998,1",N,"12475,86",100.0,10,2011
13,53,1709,24440,647,17531,104,Caixa Econômica Federal,"3998,1",N,"12475,86",100.0,10,2011
14,44,2143,19834,236,57174,104,Caixa Econômica Federal,"4447,05",N,"36927,48",100.0,7,2010
15,44,2486,19906,508,67959,104,Caixa Econômica Federal,"2089,66",N,"25185,48",75.0,9,2010
16,52,2486,27163,508,67959,104,Caixa Econômica Federal,"2194,19",N,"25185,48",75.0,9,2011
17,53,2486,27163,508,67959,104,Caixa Econômica Federal,"2194,19",N,"25185,48",75.0,9,2011
18,52,2646,36493,1580,118748,104,Caixa Econômica Federal,1791,N,21873,50.0,8,2011
19,53,2646,36493,1580,118748,104,Caixa Econômica Federal,1791,N,21873,50.0,8,2011
20,52,2671,28329,206,37884,104,Caixa Econômica Federal,"2206,98",N,"13391,34",100.0,6,2011
21,53,2671,28329,206,37884,104,Caixa Econômica Federal,"2206,98",N,"13391,34",100.0,6,2011
22,53,3174,42034,445,15597,104,Caixa Econômica Federal,3180,N,12748,100.0,10,2011
23,52,3274,26980,3052,72935,104,Caixa Econômica Federal,"5934,03",N,"69126,1",100.0,9,2010
24,52,3390,25837,154,99314,104,Caixa Econômica Federal,705,N,8343,50.0,6,2010
25,53,3390,48911,154,99314,104,Caixa Econômica Federal,1494,N,8343,50.0,6,2011
26,52,3513,29514,154,99316,104,Caixa Econômica Federal,1659,N,"17535,5",50.0,10,2011
27,53,3513,29514,154,99316,104,Caixa Econômica Federal,1659,N,"17535,5",50.0,10,2011
28,52,3588,23760,2944,73580,104,Caixa Econômica Federal,2700,N,12744,75.0,5,2011
29,53,3588,23760,2944,73580,104,Caixa Econômica Federal,2700,N,12744,75.0,5,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12828,53,577231,0,1815,118852,104,Caixa Econômica Federal,2375,F,"29624,24",50.0,8,2011
12829,53,577494,0,14514,6689,104,Caixa Econômica Federal,"3931,62",N,"35964,83",100.0,8,2011
12830,53,577701,0,740,5000581,104,Caixa Econômica Federal,"1538,4",F,"8113,69",100.0,7,2011
12831,53,577850,0,1172,5000314,104,Caixa Econômica Federal,3955,N,"46767,4",100.0,10,2011
12832,53,577995,0,359,10480,104,Caixa Econômica Federal,"9747,86",F,"20849,59",100.0,2,2011
12833,53,578321,0,407,53374,104,Caixa Econômica Federal,"3591,36",N,"23262,72",100.0,6,2011
12834,53,579090,0,1407,81048,104,Caixa Econômica Federal,3600,N,"47480,6",80.0,10,2011
12835,53,579185,0,1461,122410,104,Caixa Econômica Federal,"1529,16",F,"10463,79",100.0,6,2011
12836,53,579349,0,278,85176,104,Caixa Econômica Federal,"4057,59",N,"19929,81",100.0,6,2011
12837,53,579427,0,1818,100880,104,Caixa Econômica Federal,"1958,79",F,"22943,52",50.0,9,2011
12838,53,579813,0,1092,85375,104,Caixa Econômica Federal,"4186,08",F,"45753,29",100.0,9,2011
12839,53,580186,0,2944,19600,104,Caixa Econômica Federal,5814,N,"69435,66",100.0,10,2011
12840,53,580204,0,1000,112344,104,Caixa Econômica Federal,"1182,6",F,"10575,63",50.0,8,2011
12841,53,580273,0,1509,1074019,104,Caixa Econômica Federal,2160,F,"19469,78",100.0,8,2011
12842,53,580492,0,1101,50246,104,Caixa Econômica Federal,750,F,"1569,03",100.0,2,2011
12843,53,580572,0,1204,59826,104,Caixa Econômica Federal,"3844,5",F,"26854,19",100.0,9,2011
12844,53,581043,0,14298,7652,104,Caixa Econômica Federal,"2908,42",F,"16465,6",100.0,5,2011
12845,53,581118,0,1287,51810,104,Caixa Econômica Federal,2343,S,"4486,8",100.0,2,2011
12846,53,581215,0,267,86406,104,Caixa Econômica Federal,"2148,75",F,"25262,2",75.0,10,2011
12847,53,581506,0,113,37280,104,Caixa Econômica Federal,"4193,28",N,"18004,68",100.0,8,2011
12848,53,581515,0,1509,1074019,104,Caixa Econômica Federal,1800,F,"17485,68",100.0,8,2011
12849,53,581787,0,732,22061,104,Caixa Econômica Federal,1170,F,"5790,6",50.0,7,2011
12850,53,581951,0,752,116508,1,Banco do Brasil,"3057,12",F,"21387,78",100.0,8,2011
12851,53,582202,0,1509,26747,104,Caixa Econômica Federal,1200,F,2400,100.0,8,2011
12852,53,582628,0,14298,111416,1,Banco do Brasil,"5176,31",F,"40048,56",100.0,9,2011
12853,53,582990,0,533,1116939,104,Caixa Econômica Federal,"4790,73",S,"30443,84",100.0,10,2011
12854,53,583266,0,255,22009,1,Banco do Brasil,1452,F,6198,100.0,8,2011
12855,53,583986,0,1847,80330,104,Caixa Econômica Federal,"3570,3",F,"26593,14",100.0,7,2011
12856,53,586087,0,236,92736,104,Caixa Econômica Federal,"2092,5",N,"3975,75",75.0,2,2011
12857,53,590129,0,587,1076720,104,Caixa Econômica Federal,"2522,14",N,"26103,45",100.0,8,2011

In [30]:
#3, mostrar todos os processos feitos para estudantes casados, só que com menos colunas porque não tinha necessidade de copiar tudo
con.commit()
sqlquery="""
select distinct CO_INSCRICAO, CO_PROCESSO, CO_ADITAMENTO from
(select * from Estudante join Processo where CO_INSCRICAO=CO_INSCRICAO_EXT_ALUNOS)
where CO_ESTADO_CIVIL=2
order by CO_INSCRICAO
"""
dfq1 = pd.read_sql_query(sqlquery,con)
dfq1

       CO_INSCRICAO  CO_PROCESSO  CO_ADITAMENTO
0               643           52          27065
1               643           53          27065
2              1050           53              0
3              1342           52          27070
4              1342           53          27070
5              1372           53          43322
6              1483           52          25182
7              1483           53          46205
8              1488           44          19832
9              1554           53              0
10             1625           53              0
11             1703           52          25587
12             1709           52          24440
13             1709           53          24440
14             2143           44          19834
15             2486           44          19906
16             2486           52          27163
17             2486           53          27163
18             2646           52          36493
19             2646           53          36493
20             2671           52          28329
21             2671           53          28329
22             3174           53          42034
23             3274           52          26980
24             3390           52          25837
25             3390           53          48911
26             3513           52          29514
27             3513           53          29514
28             3588           52          23760
29             3588           53          23760
...             ...          ...            ...
12828        577231           53              0
12829        577494           53              0
12830        577701           53              0
12831        577850           53              0
12832        577995           53              0
12833        578321           53              0
12834        579090           53              0
12835        579185           53              0
12836        579349           53              0
12837        579427           53              0
12838        579813           53              0
12839        580186           53              0
12840        580204           53              0
12841        580273           53              0
12842        580492           53              0
12843        580572           53              0
12844        581043           53              0
12845        581118           53              0
12846        581215           53              0
12847        581506           53              0
12848        581515           53              0
12849        581787           53              0
12850        581951           53              0
12851        582202           53              0
12852        582628           53              0
12853        582990           53              0
12854        583266           53              0
12855        583986           53              0
12856        586087           53              0
12857        590129           53              0

[12858 rows x 3 columns]

In [39]:
#4  -- mostrar todas as faculdades com cursos de Sistemas de Informação
con.commit()
sqlquery="""
select distinct NO_IES from IES 
where CO_IES in
(select CO_IES from Curso 
where DS_CURSO='SISTEMAS DE INFORMAÇÃO' or DS_CURSO='SISTEMA DE INFORMAÇÃO')
"""
dfq1 = pd.read_sql_query(sqlquery,con)
dfq1

                                                NO_IES
0           PONTIFÍCIA UNIVERSIDADE CATÓLICA DO PARANÁ
1                        UNIVERSIDADE DE CAXIAS DO SUL
2                UNIVERSIDADE DO VALE DO RIO DOS SINOS
3         PONTIFÍCIA UNIVERSIDADE CATÓLICA DE CAMPINAS
4    PONTIFÍCIA UNIVERSIDADE CATÓLICA DO RIO GRANDE...
5                                 UNIVERSIDADE FEEVALE
6                    UNIVERSIDADE REGIONAL DE BLUMENAU
7    CENTRO UNIVERSITÁRIO PARA O DESENVOLVIMENTO DO...
8                  UNIVERSIDADE DA REGIÃO DE JOINVILLE
9              UNIVERSIDADE DO OESTE DE SANTA CATARINA
10                     CENTRO UNIVERSITÁRIO DE BRUSQUE
11                             UNIVERSIDADE DE UBERABA
12                            UNIVERSIDADE DE SOROCABA
13                          UNIVERSIDADE ESTÁCIO DE SÁ
14                       UNIVERSIDADE VEIGA DE ALMEIDA
15   FAI - CENTRO DE ENSINO SUPERIOR EM GESTÃO, TEC...
16                 UNIVERSIDADE METODISTA DE SÃO PAULO
17                         UNIVERSIDADE CASTELO BRANCO
18            FACULDADE DE EDUCAÇÃO SUPERIOR DO PARANÁ
19                        UNIVERSIDADE SÃO JUDAS TADEU
20                      UNIVERSIDADE DE RIBEIRÃO PRETO
21                 CENTRO UNIVERSITÁRIO DE VOTUPORANGA
22                           CENTRO UNIVERSITÁRIO FIEO
23                UNIVERSIDADE METODISTA DE PIRACICABA
24            FACULDADES INTEGRADAS ESPÍRITO SANTENSES
25                      UNIVERSIDADE DO OESTE PAULISTA
26                              FACULDADE TRÊS DE MAIO
27                  UNIVERSIDADE DA REGIÃO DA CAMPANHA
28                          UNIVERSIDADE NOVE DE JULHO
29                               UNIVERSIDADE PAULISTA
..                                                 ...
161                                   FACULDADE ATENAS
162                     FACULDADE DE JUAZEIRO DO NORTE
163                     Centro Universitário UNIFAFIBE
164            CENTRO UNIVERSITÁRIO MAURÍCIO DE NASSAU
165                      FACULDADE DE TALENTOS HUMANOS
166           FACULDADE PITÁGORAS DE DIVINÓPOLIS - FPD
167      UNIVERSIDADE COMUNITÁRIA DA REGIÃO DE CHAPECÓ
168                              FACULDADE DE MINAS BH
169                     FACULDADES INTEGRADAS DE PATOS
170             CENTRO UNIVERSITÁRIO DE PATOS DE MINAS
171                         FACULDADE PARAÍSO DO CEARÁ
172                              FACULDADE PINHALZINHO
173          CENTRO UNIVERSITÁRIO EURÍPEDES DE MARÍLIA
174                             FACULDADE DOM PEDRO II
175            CENTRO UNIVERSITÁRIO AUTÔNOMO DO BRASIL
176  CENTRO UNIVERSITÁRIO DA FUNDAÇÃO EDUCACIONAL D...
177           FACULDADE DE COMPUTAÇÃO DE MONTES CLAROS
178                         CENTRO UNIVERSITÁRIO SENAC
179                 CENTRO UNIVERSITÁRIO BARRIGA VERDE
180                  FACULDADES INTEGRADAS BARROS MELO
181                   FACULDADES INTEGRADAS DE ITARARÉ
182  FACULDADE DE CIÊNCIAS HUMANAS, ECONÔMICAS E DA...
183                     FACULDADES INTEGRADAS PAULISTA
184                                  FACULDADE FORTIUM
185                   FACULDADES INTEGRADAS DE TAQUARA
186                Faculdades Unificadas de Cataguases
187             Faculdades Unificadas de Teófilo Otoni
188                   LIBERTAS - FACULDADES INTEGRADAS
189         FACULDADE EDUCACIONAL DE FRANCISCO BELTRÃO
190                     FACULDADE ÁLIS DE BOM DESPACHO

[191 rows x 1 columns]

In [1]:
#4  -- mostrar todas as faculdades com cursos de Sistemas de Informação
con.commit()
sqlquery="""
select distinct NO_IES from 
(IES natural join Curso)
where DS_CURSO='SISTEMAS DE INFORMAÇÃO' or DS_CURSO='SISTEMA DE INFORMAÇÃO'
"""
dfq1 = pd.read_sql_query(sqlquery,con)
dfq1

NameError: name 'con' is not defined

In [ ]:
#4  -- mostrar todas as faculdades com cursos de Sistemas de Informação
con.commit()
sqlquery="""
select CO_INSCRICAO_EXT_ALUNOS from Estudante
where CO_INSCRICAO_EXT_ALUNOS in (
select CO_INSCRICAO from Processo
where VL_MENSALIDADE_EXT_ALUNOS>75)
"""
dfq1 = pd.read_sql_query(sqlquery,con)
dfq1